<?php

/**
 * Class Definition for: 'Kunde'
 * This file is generated by the tool `sqlgen`. Please do not update this file directly but change the respective <database>.xml file
 * and re-generate with `sqlgen`.
 */

require_once( "Adr.php") ;
require_once( "Lief.php") ;
require_once( "Kunde.php") ;

class Receiver extends	EISSCoreObject	{

	public	$AdrNr ;
	public	$AdrKontaktNr ;
	public	$FirmaName1 ;
	public	$FirmaName2 ;
	public	$PLZ ;
	public	$Ort ;
	public	$Strasse ;
	public	$Hausnummer ;
	public	$Land ;
	public	$Sprache ;		// combined language/country code, e.g. de_de, de_ch, en_us, en_uk, fr_fr, fr_ca
	public	$lC ;			// language code, e.g. de, fr, en
	public	$cC ;			// country code, e.g. de, fr, ca, us, uk
	public	$AdrZusatz ;
	public	$Funktion ;
	public	$Anrede ;
	public	$Titel ;
	public	$Vorname ;
	public	$Name ;
	public	$EigeneKundenNr ;
	public	$Tax ;
	public	$Currency ;
	public	$myAdrTyp ;

	const	ADR			= 1 ;
	const	ADRKUNDE	= 2 ;
	const	ADRLIEF		= 3 ;
	private	static	$rAdrTyp	=	array (
						Receiver::ADR		=> "Adresse",
						Receiver::ADRKUNDE	=> "Kunde",
						Receiver::ADRLIEF	=> "Lieferant"
					) ;
	/**
	 *
	 */
	function	__construct() {
		EISSCoreObject::__construct( "Receiver") ;
	}
	/**
	 *
	 */
	function	setFromKunde( $_kundeNr, $_kundeKontaktNr) {
		try {
			$this->myAdrType	=	Receiver::ADRKUNDE ;
			$this->AdrNr	=	$_kundeNr ;
			$this->AdrKontaktNr	=	$_kundeKontaktNr ;
			/**
			 *
			 */
			$this->myKunde	=	new Kunde() ;
			$this->myKunde->setKundeNr( $_kundeNr) ;

			$this->FirmaName1	=	$this->myKunde->FirmaName1 ;
			$this->FirmaName2	=	$this->myKunde->FirmaName2 ;
			$this->PLZ	=	$this->myKunde->PLZ ;
			$this->Ort	=	$this->myKunde->Ort ;
			$this->Strasse	=	$this->myKunde->Strasse ;
			$this->Hausnummer	=	$this->myKunde->Hausnummer ;
			$this->Land	=	$this->myKunde->Land ;
			$this->Sprache	=	$this->myKunde->Sprache ;
			$this->Telefon	=	$this->myKunde->Telefon ;
			$this->FAX	=	$this->myKunde->FAX ;
			$this->eMail	=	$this->myKunde->eMail ;
			$this->Tax	=	$this->myKunde->Tax ;
			$this->Currency	=	$this->myKunde->Currency ;

			/**
			 *
			 */
			$this->myKundeKontakt	=	new KundeKontakt() ;
			$this->myKundeKontakt->setKundeKontaktNr( $_kundeNr, $_kundeKontaktNr) ;

			$this->Funktion	=	$this->myKundeKontakt->Funktion ;
			$this->Anrede	=	$this->myKundeKontakt->Anrede ;
			$this->Titel	=	$this->myKundeKontakt->Titel ;
			$this->Vorname	=	$this->myKundeKontakt->Vorname ;
			$this->Name	=	$this->myKundeKontakt->Name ;

			/**
			 *
			 */
			$this->setCodes() ;

		} catch ( Exception $e) {
			throw $e ;
		}
	}
	/**
	 *
	 */
	function	setFromKKId( $_kundeKontaktId) {
		$this->myKundeKontakt	=	new KundeKontakt() ;
		$this->myKundeKontakt->setId( intval( $_kundeKontaktId)) ;
		$this->myKunde	=	new Kunde() ;
		$this->myKunde->setKundeNr( $this->myKundeKontakt->KundeNr) ;
		$this->myAdrType	=	Receiver::ADRKUNDE ;
		$this->AdrNr	=	$this->myKunde->KundeNr ;
		$this->AdrKontaktNr	=	$this->myKundeKontakt->KundeKontaktNr ;

		$this->FirmaName1	=	$this->myKunde->FirmaName1 ;
		$this->FirmaName2	=	$this->myKunde->FirmaName2 ;
		$this->PLZ	=	$this->myKunde->PLZ ;
		$this->Ort	=	$this->myKunde->Ort ;
		$this->Strasse	=	$this->myKunde->Strasse ;
		$this->Hausnummer	=	$this->myKunde->Hausnummer ;
		$this->Land	=	$this->myKunde->Land ;
		$this->Anrede	=	$this->myKundeKontakt->Anrede ;
		$this->Titel	=	$this->myKundeKontakt->Titel ;
		$this->Vorname	=	$this->myKundeKontakt->Vorname ;
		$this->Name	=	$this->myKundeKontakt->Name ;

		$this->setCodes() ;
	}

	/**
	 *
	 */
	function	setFromLKId( $_liefKontaktId) {

		$myLiefKontakt	=	new LiefKontakt() ;
		$myLiefKontakt->setId( intval( $_liefKontaktId)) ;

		$myLief	=	new Lief() ;
		$myLief->setLiefNr( $myLiefKontakt->LiefNr) ;

		$this->myAdrType	=	Receiver::ADRLIEF ;
		$this->AdrNr	=	$myLief->LiefNr ;
		$this->AdrKontaktNr	=	$myLiefKontakt->LiefKontaktNr ;

		$this->FirmaName1	=	$myLief->FirmaName1 ;
		$this->FirmaName2	=	$myLief->FirmaName2 ;
		$this->PLZ	=	$myLief->PLZ ;
		$this->Ort	=	$myLief->Ort ;
		$this->Strasse	=	$myLief->Strasse ;
		$this->Hausnummer	=	$myLief->Hausnummer ;
		$this->Land	=	$myLief->Land ;
		$this->Anrede	=	$myLiefKontakt->Anrede ;
		$this->Titel	=	$myLiefKontakt->Titel ;
		$this->Vorname	=	$myLiefKontakt->Vorname ;
		$this->Name	=	$myLiefKontakt->Name ;

		$this->setCodes() ;
	}

	/**
	 *
	 */
	function	setFromAKId( $_adrKontaktId) {

		$myAdrKontakt	=	new AdrKontakt() ;
		$myAdrKontakt->setId( intval( $_adrKontaktId)) ;

		$myAdr	=	new Adr() ;
		$myAdr->setAdrNr( $myAdrKontakt->AdrNr) ;

		$this->myAdrType	=	Receiver::ADR ;
		$this->AdrNr	=	$myAdr->AdrNr ;
		$this->AdrKontaktNr	=	$myAdrKontakt->AdrKontaktNr ;

		$this->FirmaName1	=	$myAdr->FirmaName1 ;
		$this->FirmaName2	=	$myAdr->FirmaName2 ;
		$this->PLZ	=	$myAdr->PLZ ;
		$this->Ort	=	$myAdr->Ort ;
		$this->Strasse	=	$myAdr->Strasse ;
		$this->Hausnummer	=	$myAdr->Hausnummer ;
		$this->Land	=	$myAdr->Land ;
		$this->Anrede	=	$myAdrKontakt->Anrede ;
		$this->Titel	=	$myAdrKontakt->Titel ;
		$this->Vorname	=	$myAdrKontakt->Vorname ;
		$this->Name	=	$myAdrKontakt->Name ;

		$this->setCodes() ;
	}

	/**
	 *
	 */
	function	setFromLief( $_liefNr, $_liefKontaktNr) {

		$myLief	=	new Lief() ;
		$myLief->LiefNr	=	$_liefNr ;
		$myLief->fetchFromDb() ;

		$myLiefKontakt	=	new LiefKontakt() ;
		$myLiefKontakt->LiefNr	=	$_liefNr ;
		$myLiefKontakt->LiefKontaktNr	=	$_liefKontaktNr ;
		$myLiefKontakt->fetchFromDbByAll() ;

		$this->FirmaName1	=	$myLief->FirmaName1 ;
		$this->FirmaName2	=	$myLief->FirmaName2 ;
		$this->PLZ	=	$myLief->PLZ ;
		$this->Ort	=	$myLief->Ort ;
		$this->Strasse	=	$myLief->Strasse ;
		$this->Hausnummer	=	$myLief->Hausnummer ;
		$this->Land	=	$myLief->Land ;
		$this->Sprache	=	$myLief->Sprache ;
		$this->Telefon	=	$myLief->Telefon ;
		$this->FAX	=	$myLief->FAX ;
		$this->eMail	=	$myLief->eMail ;
		$this->EigeneKundenNr	=	$myLief->EigeneKundenNr ;
		$this->Tax	=	$myLief->Tax ;
		$this->Currency	=	$myLief->Currency ;

		$this->Anrede	=	$myLiefKontakt->Anrede ;
		$this->Titel	=	$myLiefKontakt->Titel ;
		$this->Vorname	=	$myLiefKontakt->Vorname ;
		$this->Name	=	$myLiefKontakt->Name ;

		$this->setCodes() ;
	}

	/**
	 *
	 */
	function	setFromAdr( $_adrNr, $_adrKontaktNr) {

		$myAdr	=	new Adr() ;
		$myAdr->AdrNr	=	$_adrNr ;
		$myAdr->fetchFromDb() ;

		$myAdrKontakt	=	new AdrKontakt() ;
		$myAdrKontakt->AdrNr	=	$_adrNr ;
		$myAdrKontakt->AdrKontaktNr	=	$_adrKontaktNr ;
		$myAdrKontakt->fetchFromDbByAll() ;

		$this->FirmaName1	=	$myAdr->FirmaName1 ;
		$this->FirmaName2	=	$myAdr->FirmaName2 ;
		$this->PLZ	=	$myAdr->PLZ ;
		$this->Ort	=	$myAdr->Ort ;
		$this->Strasse	=	$myAdr->Strasse ;
		$this->Hausnummer	=	$myAdr->Hausnummer ;
		$this->Land	=	$myAdr->Land ;
		$this->Sprache	=	$myAdr->Sprache ;
		$this->Telefon	=	$myAdr->Telefon ;
		$this->FAX	=	$myAdr->FAX ;
		$this->eMail	=	$myAdr->eMail ;

		$this->Anrede	=	$myAdrKontakt->Anrede ;
		$this->Titel	=	$myAdrKontakt->Titel ;
		$this->Vorname	=	$myAdrKontakt->Vorname ;
		$this->Name	=	$myAdrKontakt->Name ;

		$this->setCodes() ;
	}
	/**
	 *
	 */
	function	getZHd() {

		$rcvrBlock	=	"" ;
		
		switch( $this->Anrede) {
		case	"Herr"	:
		case	"Mr."	:
		case	"Mr"	:
			switch ( $this->lC) {
			case	"de"	:
				$rcvrBlock	.=	"z.Hd. Herrn" ;
				if ( strlen( $this->Titel) > 0)		$rcvrBlock	.=	" " . $this->Titel ;
				if ( strlen( $this->Vorname) > 0)	$rcvrBlock	.=	" " . $this->Vorname ;
				if ( strlen( $this->Name) > 0)		$rcvrBlock	.=	" " . $this->Name ;
				break ;
			case	"en"	:
				$rcvrBlock	.=	"Attn Mr" ;
				if ( strlen( $this->Titel) > 0)		$rcvrBlock	.=	" " . $this->Titel ;
				if ( strlen( $this->Vorname) > 0)	$rcvrBlock	.=	" " . $this->Vorname ;
				if ( strlen( $this->Name) > 0)		$rcvrBlock	.=	" " . $this->Name ;
				break ;
			default	:
				switch ( $this->Funktion) {
				case	"FBLBIA"	:
					$rcvrBlock	.=	"Fachbereich Biologie" ;
					break ;
				case	"FBLCHA"	:
					$rcvrBlock	.=	"Fachbereich Chemie" ;
					break ;
				case	"FBLPHA"	:
					$rcvrBlock	.=	"Fachbereich Physik" ;
					break ;
				default	:
					$rcvrBlock	.=	$this->AdrZusatz ;
					break ;
				}
				break ;
			}
			break ;
		case	"Frau"	:
		case	"Mrs."	:
		case	"Mrs"	:
		case	"Ms."	:
		case	"Ms"	:
			switch ( $this->lC) {
			case	"de"	:
				$rcvrBlock	.=	"z.Hd. Frau" ;
				if ( strlen( $this->Titel) > 0)		$rcvrBlock	.=	" " . $this->Titel ;
				if ( strlen( $this->Vorname) > 0)	$rcvrBlock	.=	" " . $this->Vorname ;
				if ( strlen( $this->Name) > 0)		$rcvrBlock	.=	" " . $this->Name ;
				break ;
			case	"en"	:
				$rcvrBlock	.=	"Attn Mrs" ;
				if ( strlen( $this->Titel) > 0)		$rcvrBlock	.=	" " . $this->Titel ;
				if ( strlen( $this->Vorname) > 0)	$rcvrBlock	.=	" " . $this->Vorname ;
				if ( strlen( $this->Name) > 0)		$rcvrBlock	.=	" " . $this->Name ;
				break ;
			default	:
				switch ( $this->Funktion) {
				case	"FBLBIA"	:
					$rcvrBlock	.=	"Fachbereich Biologie" ;
					break ;
				case	"FBLCHA"	:
					$rcvrBlock	.=	"Fachbereich Chemie" ;
					break ;
				case	"FBLPHA"	:
					$rcvrBlock	.=	"Fachbereich Physik" ;
					break ;
				default	:
					$rcvrBlock	.=	$this->AdrZusatz ;
					break ;
				}
				break ;
			}
			break ;
		default	:
			switch ( $this->Funktion) {
			case	"FBLBIA"	:
				$rcvrBlock	.=	"Fachbereich Biologie" ;
				break ;
			case	"FBLCHA"	:
				$rcvrBlock	.=	"Fachbereich Chemie" ;
				break ;
			case	"FBLPHA"	:
				$rcvrBlock	.=	"Fachbereich Physik" ;
				break ;
			default	:
				$rcvrBlock	.=	$this->AdrZusatz ;
				break ;
			}
			break ;
		}
		return( $rcvrBlock) ;
	}
	/**
	 *
	 */
	function	getForDisp() {
		$buf	=	"" ;
		$buf	.=	$this->FirmaName1 ;
		if ( strlen( $this->FirmaName2) > 0)		$buf	.=	" " . $this->FirmaName2 ;
		if ( strlen( $this->Anrede) > 0)		$buf	.=	" " . $this->Anrede ;
		if ( strlen( $this->Vorname) > 0)		$buf	.=	" " . $this->Vorname ;
		if ( strlen( $this->Name) > 0)		$buf	.=	" " . $this->Name ;
		return $buf ;
	}
	/**
	 *
	 */
	function	setCodes() {
		$buf	=	explode( "_", $this->Sprache) ;
		$this->lC	=	$buf[0] ;
		if ( isset( $buf[1])) {
			$this->cC	=	$buf[1] ;
		} else {
			$this->cC	=	"de" ;
		}
	}
	/**
	 *
	 */
	function	getRAdrTyp() {
		return  self::$rAdrTyp ;
	}
	/**
	 *
	 */
	function	getAddrStreet() {
		switch ( $this->Land) {
		case	"de"	:
			return $this->Strasse . " " . $this->Hausnummer ;
			break ;
		case	"uk"	:
			return $this->Hausnummer . " " . $this->Strasse ;
			break ;
		default	:
			return $this->Strasse . " " . $this->Hausnummer ;
			break ;
		}
	}
	/**
	 *
	 */
	function	getAddrCity() {
		switch ( $this->Land) {
		case	"de"	:
			return $this->PLZ . " " . $this->Ort ;
			break ;
		case	"uk"	:
			return $this->Ort . " " . $this->PLZ ;
			break ;
		default	:
			return $this->PLZ . " " . $this->Ort ;
			break ;
		}
	}
	/**
	 *
	 */
	function	getAddrCountry() {
		switch ( $this->Land) {
		case	""		:
			return "" ;
			break ;
		case	"de"	:
			return "" ;
			break ;
		default	:
			$laender	=	Opt::getRLaender() ;
			return $laender[ $this->Land] ;
			break ;
		}
	}
	function	getAddrLine() {
		$res	=	"" ;
		if ( strlen( $this->Anrede) > 0 && strlen( $this->Name) > 0) {
			switch( $this->Anrede) {
			case	"Herr"	:
				$res	.=	"z.Hd. Herrn" ;
				break ;
			case	"Frau"	:
				$res	.=	"z.Hd. Frau" ;
				break ;
			case	"Mr."	:
				$res	.=	"Attn. Mr." ;
				break ;
			case	"Mrs."	:
				$res	.=	"Attn. Mrs." ;
				break ;
			case	"Ms."	:
				$res	.=	"Attn. Ms." ;
				break ;
			default	:
				break ;
			}
			if ( strlen( $this->Titel) > 0)		$res	.=	" " . $this->Titel ;
			if ( strlen( $this->Vorname) > 0)	$res	.=	" " . $this->Vorname ;
			if ( strlen( $this->Name) > 0)		$res	.=	" " . $this->Name ;
		}
		return $res ;
	}
	/**
	 *
	 */
	function	getAnrede() {
		$res	=	"" ;
		if ( strlen( $this->Anrede) > 0 && strlen( $this->Name) > 0) {
			switch ( $this->Anrede) {
			case	"Herr"	:
				$res	=	sprintf( "Sehr geehrter Herr %s %s", $this->Titel, $this->Name) ;
				break ;
			case	"Frau"	:
				$res	=	sprintf( "Sehr geehrte Frau %s %s", $this->Titel, $this->Name) ;
				break ;
			case	"Mr."	:
				$res	=	sprintf( "Dear Mr. %s", $this->Name) ;
				break ;
			case	"Mrs."	:
				$res	=	sprintf( "Dear Mrs. %s", $this->Name) ;
				break ;
			}
		} else {
			$res	=	"Sehr geehrte Damen und Herren" ;
		}
		return str_replace( "  ", " ", $res) ;
	}
	/**
	 * 
	 */
	function	getAsXML() {
		$ret	=	"" ;

		$ret	.=	"<KundeAdr>\n" ;
//		$ret	.=	"<Kunde>\n" ;
//		$ret	.=	"<FirmaName1><![CDATA[" . $this->FirmaName1 . "]]></FirmaName1>\n" ;
//		$ret	.=	"<FirmaName2><![CDATA[" . $this->FirmaName2 . "]]></FirmaName2>\n" ;
//		$ret	.=	"</Kunde>\n" ;
//		$ret	.=	"<KundeKontakt>\n" ;
//		$ret	.=	"</KundeKontakt>\n" ;
//		$ret	.=	"<CustAttnLine>".$this->myKundeKontakt->getAddrLine()."</CustAttnLine>\n" ;
//		$ret	.=	"<CustOpngLine>".$this->myKundeKontakt->getAnrede()."</CustOpngLine>\n" ;
		if ( isset( $this->myKunde)) {
			$ret	.=	$this->myKunde->getXMLF() ;
			$ret	.=	$this->myKundeKontakt->getXMLF() ;
		}
		$ret	.=	"</KundeAdr>\n" ;
		return $ret ;
	}
	/**
	 *
	 */
	function	getPosBer() {
		switch ( $this->Funktion . "-" . $this->Anrede) {
		case	"FBLBI-Herr"	:
			$posBerText	=	"Fachbereichsleiter Biologie " ;
			break ;
		case	"FBLBI-Frau"	:
			$posBerText	=	"Fachbereichsleiterin Biologie " ;
			break ;
		case	"FBLCH-Herr"	:
			$posBerText	=	"Fachbereichsleiter Chemie " ;
			break ;
		case	"FBLCH-Frau"	:
			$posBerText	=	"Fachbereichsleiterin Chemie " ;
			break ;
		case	"FBLPH-Herr"	:
			$posBerText	=	"Fachbereichsleiter Physik " ;
			break ;
		case	"FBLPH-Frau"	:
			$posBerText	=	"Fachbereichsleiterin Physik " ;
			break ;
		case	"FBBI-Herr"	:
			$posBerText	=	"Verantwortlicher Fachbereich Biologie " ;
			break ;
		case	"FBBI-Frau"	:
			$posBerText	=	"Verantwortliche Fachbereich Biologie " ;
			break ;
		case	"FBCH-Herr"	:
			$posBerText	=	"Verantwortlicher Fachbereich Chemie " ;
			break ;
		case	"FBCH-Frau"	:
			$posBerText	=	"Verantwortliche Fachbereich Chemie " ;
			break ;
		case	"FBPH-Herr"	:
			$posBerText	=	"Verantwortlicher Fachbereich Physik " ;
			break ;
		case	"FBPH-Frau"	:
			$posBerText	=	"Verantwortliche Fachbereich Physik " ;
			break ;
		case	"FBLBIA-Herr"	:
			$posBerText	=	"Verantwortlicher Fachbereich Biologie " ;
			break ;
		case	"FBLBIA-Frau"	:
			$posBerText	=	"Verantwortliche Fachbereich Biologie " ;
			break ;
		case	"FBLBIA-"	:
			$posBerText	=	"Verantwortliche(r) Fachbereich Biologie " ;
			break ;
		case	"FBLCHA-Herr"	:
			$posBerText	=	"Verantwortlicher Fachbereich Chemie " ;
			break ;
		case	"FBLCHA-Frau"	:
			$posBerText	=	"Verantwortliche Fachbereich Chemie " ;
			break ;
		case	"FBLCHA-"	:
			$posBerText	=	"Verantwortliche(r) Fachbereich Chemie " ;
			break ;
		case	"FBLPHA-Herr"	:
			$posBerText	=	"Verantwortlicher Fachbereich Physik " ;
			break ;
		case	"FBLPHA-Frau"	:
			$posBerText	=	"Verantwortliche Fachbereich Physik " ;
			break ;
		case	"FBLPHA-"	:
			$posBerText	=	"Verantwortliche(r) Fachbereich Physik " ;
			break ;
		default	:
			$posBerText	=	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX " ;
			break ;
		}
		return $posBerText ;
	}
}

?>
