<?php

#
# Class Definition for: 'Kunde'
# This file is generated by the tool `sqlgen`. Please do not update this file directly but change the respective <database>.xml file
# and re-generate with `sqlgen`.
#

require_once( "Adr.php") ;

require_once( "Lief.php") ;

require_once( "Kunde.php") ;

class Receiver {

	public	$FirmaName1 ;
	public	$FirmaName2 ;
	public	$PLZ ;
	public	$Ort ;
	public	$Strasse ;
	public	$Hausnummer ;
	public	$Land ;
	public	$Sprache ;		// combined language/country code, e.g. de_de, de_ch, en_us, en_uk, fr_fr, fr_ca
	public	$lC ;			// language code, e.g. de, fr, en
	public	$cC ;			// country code, e.g. de, fr, ca, us, uk
	public	$AdrZusatz ;
	public	$Anrede ;
	public	$Titel ;
	public	$Vorname ;
	public	$Name ;
	public	$EigeneKundenNr ;
	public	$Tax ;
	public	$Currency ;

	function	__construct() {
	}

	function	setFromKunde( $_kundeNr, $_kundeKontaktNr) {

		$myKunde	=	new Kunde() ;
		$myKunde->KundeNr	=	$_kundeNr ;
		$myKunde->fetchFromDb() ;

		$myKundeKontakt	=	new KundeKontakt() ;
		$myKundeKontakt->KundeNr	=	$_kundeNr ;
		$myKundeKontakt->KundeKontaktNr	=	$_kundeKontaktNr ;
		$myKundeKontakt->fetchFromDbByAll() ;

		$this->FirmaName1	=	$myKunde->FirmaName1 ;
		$this->FirmaName2	=	$myKunde->FirmaName2 ;
		$this->PLZ	=	$myKunde->PLZ ;
		$this->Ort	=	$myKunde->Ort ;
		$this->Strasse	=	$myKunde->Strasse ;
		$this->Hausnummer	=	$myKunde->Hausnummer ;
		$this->Land	=	$myKunde->Land ;
		$this->Sprache	=	$myKunde->Sprache ;
		$this->Telefon	=	$myKunde->Telefon ;
		$this->FAX	=	$myKunde->FAX ;
		$this->eMail	=	$myKunde->eMail ;
		$this->Tax	=	$myKunde->Tax ;
		$this->Currency	=	$myKunde->Currency ;

		$this->Anrede	=	$myKundeKontakt->Anrede ;
		$this->Titel	=	$myKundeKontakt->Titel ;
		$this->Vorname	=	$myKundeKontakt->Vorname ;
		$this->Name	=	$myKundeKontakt->Name ;

		$this->setCodes() ;
	}

	function	setFromKKId( $_kundeKontaktId) {

		$myKundeKontakt	=	new KundeKontakt() ;
		$myKundeKontakt->Id	=	$_kundeKontaktId ;
		$myKundeKontakt->fetchFromDbById() ;

		$myKunde	=	new Kunde() ;
		$myKunde->KundeNr	=	$myKundeKontakt->KundeNr ;
		$myKunde->fetchFromDb() ;

		$this->FirmaName1	=	$myKunde->FirmaName1 ;
		$this->FirmaName2	=	$myKunde->FirmaName2 ;
		$this->PLZ	=	$myKunde->PLZ ;
		$this->Ort	=	$myKunde->Ort ;
		$this->Strasse	=	$myKunde->Strasse ;
		$this->Hausnummer	=	$myKunde->Hausnummer ;
		$this->Land	=	$myKunde->Land ;
		$this->Anrede	=	$myKundeKontakt->Anrede ;
		$this->Titel	=	$myKundeKontakt->Titel ;
		$this->Vorname	=	$myKundeKontakt->Vorname ;
		$this->Name	=	$myKundeKontakt->Name ;

		$this->setCodes() ;
	}

	function	setFromLief( $_liefNr, $_liefKontaktNr) {

		$myLief	=	new Lief() ;
		$myLief->LiefNr	=	$_liefNr ;
		$myLief->fetchFromDb() ;

		$myLiefKontakt	=	new LiefKontakt() ;
		$myLiefKontakt->LiefNr	=	$_liefNr ;
		$myLiefKontakt->LiefKontaktNr	=	$_liefKontaktNr ;
		$myLiefKontakt->fetchFromDbByAll() ;

		$this->FirmaName1	=	$myLief->FirmaName1 ;
		$this->FirmaName2	=	$myLief->FirmaName2 ;
		$this->PLZ	=	$myLief->PLZ ;
		$this->Ort	=	$myLief->Ort ;
		$this->Strasse	=	$myLief->Strasse ;
		$this->Hausnummer	=	$myLief->Hausnummer ;
		$this->Land	=	$myLief->Land ;
		$this->Sprache	=	$myLief->Sprache ;
		$this->Telefon	=	$myLief->Telefon ;
		$this->FAX	=	$myLief->FAX ;
		$this->eMail	=	$myLief->eMail ;
		$this->EigeneKundenNr	=	$myLief->EigeneKundenNr ;
		$this->Tax	=	$myLief->Tax ;
		$this->Currency	=	$myLief->Currency ;

		$this->Anrede	=	$myLiefKontakt->Anrede ;
		$this->Titel	=	$myLiefKontakt->Titel ;
		$this->Vorname	=	$myLiefKontakt->Vorname ;
		$this->Name	=	$myLiefKontakt->Name ;

		$this->setCodes() ;
	}

	function	setFromAdr( $_adrNr, $_adrKontaktNr) {

		$myAdr	=	new Adr() ;
		$myAdr->AdrNr	=	$_adrNr ;
		$myAdr->fetchFromDb() ;

		$myAdrKontakt	=	new AdrKontakt() ;
		$myAdrKontakt->AdrNr	=	$_adrNr ;
		$myAdrKontakt->AdrKontaktNr	=	$_adrKontaktNr ;
		$myAdrKontakt->fetchFromDbByAll() ;

		$this->FirmaName1	=	$myAdr->FirmaName1 ;
		$this->FirmaName2	=	$myAdr->FirmaName2 ;
		$this->PLZ	=	$myAdr->PLZ ;
		$this->Ort	=	$myAdr->Ort ;
		$this->Strasse	=	$myAdr->Strasse ;
		$this->Hausnummer	=	$myAdr->Hausnummer ;
		$this->Land	=	$myAdr->Land ;
		$this->Sprache	=	$myAdr->Sprache ;
		$this->Telefon	=	$myAdr->Telefon ;
		$this->FAX	=	$myAdr->FAX ;
		$this->eMail	=	$myAdr->eMail ;

		$this->Anrede	=	$myAdrKontakt->Anrede ;
		$this->Titel	=	$myAdrKontakt->Titel ;
		$this->Vorname	=	$myAdrKontakt->Vorname ;
		$this->Name	=	$myAdrKontakt->Name ;

		$this->setCodes() ;
	}

	function	getAdrAsTeX() {

		$rcvrBlock	=	"" ;

		switch ( $this->cC) {
		case	"de"	:
			$rcvrBlock	.=	sprintf( "%s\\\\\n", mTS( $this->FirmaName1)) ;
			$rcvrBlock	.=	sprintf( "%s\\\\\n", mTS( $this->FirmaName2)) ;
			$rcvrBlock	.=	$this->getContactAsTeX() ;
			$rcvrBlock	.=	sprintf( "%s %s\\\\\n", mTS( $this->Strasse), mTS( $this->Hausnummer)) ;
			$rcvrBlock	.=	sprintf( "%s %s\\\\", mTS( $this->PLZ), mTS( $this->Ort)) ;
			break ;
		case	"us"	:
			$rcvrBlock	.=	sprintf( "%s\\\\\n", mTS( $this->FirmaName1)) ;
			$rcvrBlock	.=	sprintf( "%s\\\\\n", mTS( $this->FirmaName2)) ;
			$rcvrBlock	.=	$this->getContactAsTeX() ;
			$rcvrBlock	.=	sprintf( "%s %s\\\\\n", mTS( $this->Hausnummer), mTS( $this->Strasse)) ;
			$rcvrBlock	.=	sprintf( "%s, %s\\\\\n", mTS( $this->Ort), mTS( $this->PLZ)) ;
			$rcvrBlock	.=	sprintf( "%s\\\\", mTS( $this->Land)) ;
			break ;
		case	"uk"	:
			$rcvrBlock	.=	sprintf( "%s\\\\\n", mTS( $this->FirmaName1)) ;
			$rcvrBlock	.=	sprintf( "%s\\\\\n", mTS( $this->FirmaName2)) ;
			$rcvrBlock	.=	$this->getContactAsTeX() ;
			$rcvrBlock	.=	sprintf( "%s %s\\\\\n", mTS( $this->Hausnummer), mTS( $this->Strasse)) ;
			$rcvrBlock	.=	sprintf( "%s, %s\\\\\n", mTS( $this->Ort), mTS( $this->PLZ)) ;
			$rcvrBlock	.=	sprintf( "%s\\\\", mTS( $this->Land)) ;
			break ;
		default	:
			$rcvrBlock	.=	sprintf( "%s\\\\\n", mTS( $this->FirmaName1)) ;
			$rcvrBlock	.=	sprintf( "%s\\\\\n", mTS( $this->FirmaName2)) ;
			$rcvrBlock	.=	$this->getContactAsTeX() ;
			$rcvrBlock	.=	sprintf( "%s %s\\\\\n", mTS( $this->Strasse), mTS( $this->Hausnummer)) ;
			$rcvrBlock	.=	sprintf( "%s %s\\\\\n", mTS( $this->PLZ), mTS( $this->Ort)) ;
			$rcvrBlock	.=	sprintf( "%s\\\\", mTS( $this->Land)) ;
			break ;
		}
		return( $rcvrBlock) ;
	}

	function	getContactAsTeX() {

		$rcvrBlock	=	"" ;
		
		switch( $this->Anrede) {
		case	"Herr"	:
		case	"Mr."	:
		case	"Mr"	:
			switch ( $this->lC) {
			case	"de"	:
				$rcvrBlock	.=	"z.Hd. Herrn" ;
				if ( strlen( $this->Titel) > 0)		$rcvrBlock	.=	" " . $this->Titel ;
				if ( strlen( $this->Vorname) > 0)	$rcvrBlock	.=	" " . $this->Vorname ;
				if ( strlen( $this->Name) > 0)		$rcvrBlock	.=	" " . $this->Name ;
				break ;
			case	"en"	:
				$rcvrBlock	.=	"Attn Mr" ;
				if ( strlen( $this->Titel) > 0)		$rcvrBlock	.=	" " . $this->Titel ;
				if ( strlen( $this->Vorname) > 0)	$rcvrBlock	.=	" " . $this->Vorname ;
				if ( strlen( $this->Name) > 0)		$rcvrBlock	.=	" " . $this->Name ;
				break ;
			default	:
				break ;
			}
			break ;
		case	"Frau"	:
		case	"Mrs."	:
		case	"Mrs"	:
		case	"Ms."	:
		case	"Ms"	:
			switch ( $this->lC) {
			case	"de"	:
				$rcvrBlock	.=	"z.Hd. Frau" ;
				if ( strlen( $this->Titel) > 0)		$rcvrBlock	.=	" " . $this->Titel ;
				if ( strlen( $this->Vorname) > 0)	$rcvrBlock	.=	" " . $this->Vorname ;
				if ( strlen( $this->Name) > 0)		$rcvrBlock	.=	" " . $this->Name ;
				break ;
			case	"en"	:
				$rcvrBlock	.=	"Attn Mrs" ;
				if ( strlen( $this->Titel) > 0)		$rcvrBlock	.=	" " . $this->Titel ;
				if ( strlen( $this->Vorname) > 0)	$rcvrBlock	.=	" " . $this->Vorname ;
				if ( strlen( $this->Name) > 0)		$rcvrBlock	.=	" " . $this->Name ;
				break ;
			default	:
				break ;
			}
			break ;
		default	:
			break ;
		}
		$rcvrBlock	.=	"\\\\\n" ;
		return( $rcvrBlock) ;
	}

	function	getGreetingAsTeX() {

		$rcvrBlock	=	"" ;
		
//echo "gG'" . $this->lC . "'<br/>" ;
		switch( $this->Anrede) {
		case	"Herr"	:
		case	"Mr."	:
		case	"Mr"	:
			switch ( $this->lC) {
			case	"de"	:
				$rcvrBlock	.=	"Sehr geehrter Herr " ;
				if ( strlen( $this->Titel) > 0)		$rcvrBlock	.=	" " . $this->Titel ;
				if ( strlen( $this->Name) > 0)		$rcvrBlock	.=	" " . $this->Name ;
				$rcvrBlock	.=	", " ;
				break ;
			case	"en"	:
				$rcvrBlock	.=	"Dear Mr" ;
				if ( strlen( $this->Name) > 0)		$rcvrBlock	.=	" " . $this->Name ;
				$rcvrBlock	.=	", " ;
				break ;
			default	:
				break ;
			}
			break ;
		case	"Frau"	:
		case	"Mrs."	:
		case	"Mrs"	:
		case	"Ms."	:
		case	"Ms"	:
			switch ( $this->lC) {
			case	"de"	:
				$rcvrBlock	.=	"Sehr geehrte Frau" ;
				if ( strlen( $this->Titel) > 0)		$rcvrBlock	.=	" " . $this->Titel ;
				if ( strlen( $this->Name) > 0)		$rcvrBlock	.=	" " . $this->Name ;
				$rcvrBlock	.=	", " ;
				break ;
			case	"en"	:
				$rcvrBlock	.=	"Dear Mrs" ;
				if ( strlen( $this->Name) > 0)		$rcvrBlock	.=	" " . $this->Name ;
				$rcvrBlock	.=	", " ;
				break ;
			default	:
				break ;
			}
			break ;
		default	:
			switch ( $this->lC) {
			case	"de"	:
				$rcvrBlock	.=	"Sehr geehrte Damen und Herren" ;
				$rcvrBlock	.=	", " ;
				break ;
			case	"en"	:
				$rcvrBlock	.=	"Dear Ladies, Dear Sirs" ;
				$rcvrBlock	.=	", " ;
				break ;
			default	:
				break ;
			}
			break ;
		}
		$rcvrBlock	.=	"\\\\\n" ;
		return( $rcvrBlock) ;
	}

	function	getForDisp() {
		$buf	=	"" ;
		$buf	.=	$this->FirmaName1 ;
		if ( strlen( $this->FirmaName2) > 0)		$buf	.=	" " . $this->FirmaName2 ;
		if ( strlen( $this->Anrede) > 0)		$buf	.=	" " . $this->Anrede ;
		if ( strlen( $this->Vorname) > 0)		$buf	.=	" " . $this->Vorname ;
		if ( strlen( $this->Name) > 0)		$buf	.=	" " . $this->Name ;
		return $buf ;
	}

	function	setCodes() {
		$buf	=	explode( "/", $this->Sprache) ;
//echo "'" . $buf[0] . "'<br/>" ;
		$this->lC	=	$buf[0] ;
		if ( isset( $buf[1])) {
//echo ">>'" . $buf[1] . "'<br/>" ;
			$this->cC	=	$buf[1] ;
		} else {
			$this->cC	=	"de" ;
		}
	}
}

?>
