<?php
#
# Class Definition for: 'SerNo'
# This file is generated by the tool `sqlgen`. Please do not update this file directly but change the respective <database>.xml file
# and re-generate with `sqlgen`.
#

$debug	=	0 ;

class SerNo {
	var	$Id ;
	var	$ArtikelNr ;
	var	$SerNr ;
	var	$CuDlvrNo ;
	var	$_status ;
	var	$_valid ;
	var	$_currRow ;
	var	$_lastRow ;
	/**
	 * 
	 */
	function	SerNo() {
	}
	/**
	 * 
	 */
	function	getXML() {
	}
}
?>
