<?php
#
# Class Definition for: 'TmpLabels'
# This file is generated by the tool `sqlgen`. Please do not update this file directly but change the respective <database>.xml file
# and re-generate with `sqlgen`.
#

$debug	=	0 ;

class TmpLabels {
	var	$Id ;
	var	$ArtikelNr ;
	var	$ArtikelNrHerst ;
	var	$ArtikelBez1 ;
	var	$ArtikelBez2 ;
	var	$MengenText ;
	var	$VarianteBez ;
	var	$MengenEinheit ;
	var	$Gefahrenklasse ;
	var	$Aufkleber ;
	var	$MengeLabels ;
	var	$_status ;
	var	$_valid ;
	var	$_currRow ;
	var	$_lastRow ;

	function	TmpLabels() {
		$this->_status	=	0 ;
		$this->_valid	=	0 ;
		$this->_currRow	=	0 ;
		$this->_lastRow	=	0 ;
		$this->Id	=	0 ;
		$this->ArtikelNr	=	"" ;
		$this->ArtikelNrHerst	=	"" ;
		$this->ArtikelBez1	=	"" ;
		$this->ArtikelBez2	=	"" ;
		$this->MengenText	=	"" ;
		$this->VarianteBez	=	"" ;
		$this->MengenEinheit	=	"" ;
		$this->Gefahrenklasse	=	"" ;
		$this->Aufkleber	=	0 ;
		$this->MengeLabels	=	0 ;
	}

	function	getXML() {
		$buffer	=	"<TmpLabels>\n" ;
		$buffer	.=	"<Id type=\"-\">".$this->Id."</Id>\n" ; 
		$buffer	.=	"<ArtikelNr type=\"-\">".$this->ArtikelNr."</ArtikelNr>\n" ; 
		$buffer	.=	"<ArtikelNrHerst type=\"-\">".$this->ArtikelNrHerst."</ArtikelNrHerst>\n" ; 
		$buffer	.=	"<ArtikelBez1 type=\"-\">".$this->ArtikelBez1."</ArtikelBez1>\n" ; 
		$buffer	.=	"<ArtikelBez2 type=\"-\">".$this->ArtikelBez2."</ArtikelBez2>\n" ; 
		$buffer	.=	"<MengenText type=\"-\">".$this->MengenText."</MengenText>\n" ; 
		$buffer	.=	"<VarianteBez type=\"-\">".$this->VarianteBez."</VarianteBez>\n" ; 
		$buffer	.=	"<MengenEinheit type=\"-\">".$this->MengenEinheit."</MengenEinheit>\n" ; 
		$buffer	.=	"<Gefahrenklasse type=\"-\">".$this->Gefahrenklasse."</Gefahrenklasse>\n" ; 
		$buffer	.=	"<Aufkleber type=\"-\">".$this->Aufkleber."</Aufkleber>\n" ; 
		$buffer	.=	"<MengeLabels type=\"-\">".$this->MengeLabels."</MengeLabels>\n" ; 
		$buffer	.=	"</TmpLabels>\n" ;
		return( $buffer) ;
	}

	function	assignFromRow( $row) {
		$this->Id	=	intval( $row["Id"]) ;
		$this->ArtikelNr	=	$row["ArtikelNr"] ;
		$this->ArtikelNrHerst	=	$row["ArtikelNrHerst"] ;
		$this->ArtikelBez1	=	$row["ArtikelBez1"] ;
		$this->ArtikelBez2	=	$row["ArtikelBez2"] ;
		$this->MengenText	=	$row["MengenText"] ;
		$this->VarianteBez	=	$row["VarianteBez"] ;
		$this->MengenEinheit	=	$row["MengenEinheit"] ;
		$this->Gefahrenklasse	=	$row["Gefahrenklasse"] ;
		$this->Aufkleber	=	intval( $row["Aufkleber"]) ;
		$this->MengeLabels	=	intval( $row["MengeLabels"]) ;
	}

	function	storeInDb( $database) {
		$this->_status	=	0 ;
		$this->_valid	=	0 ;
		$query	=	"insert into TmpLabels ( " ;
		$query	.=	"ArtikelNr, ArtikelNrHerst, ArtikelBez1, ArtikelBez2, MengenText " ;
		$query	.=	", VarianteBez, MengenEinheit, Gefahrenklasse, Aufkleber, MengeLabels " ;
		$query	.=	") values ( " ;
		$query	.=	" '" . $this->ArtikelNr . "' " ;
		$query	.=	", '" . mysql_escape_string( $this->ArtikelNrHerst) . "' " ;
		$query	.=	", '" . mysql_escape_string( $this->ArtikelBez1) . "' " ;
		$query	.=	", '" . mysql_escape_string( $this->ArtikelBez2) . "' " ;
		$query	.=	", '" . mysql_escape_string( $this->MengenText) . "' " ;
		$query	.=	", '" . mysql_escape_string( $this->VarianteBez) . "' " ;
		$query	.=	", '" . mysql_escape_string( $this->MengenEinheit) . "' " ;
		$query	.=	", '" . mysql_escape_string( $this->Gefahrenklasse) . "' " ;
		$query	.=	", '" . $this->Aufkleber . "' " ;
		$query	.=	", '" . $this->MengeLabels . "' " ;
		$query	.=	") " ;
		$sqlResult	=	mysql_query( $query, $database) ;
		if ( !$sqlResult) {
			$this->_status  =       -1 ;
		} else {
			$this->Id	=	mysql_insert_id() ;
			$this->_valid	=	1 ;
		}
		return $this->_status ;
	}

	function	fetchFromDb( $database) {
		$this->_status	=	0 ;
		$this->_valid	=	0 ;
		$query	=	"select * " ;
		$query	.=	"from TmpLabels " ;

		if ( $this->ArtikelNr != "") {
			$query	.=	"where ArtikelNr='" . $this->ArtikelNr . "' " ;
		}
		$sqlResult      =       mysql_query( $query, $database) ;
		if ( !$sqlResult) {
			$this->_status  =       -1 ;
		} else {
			$numrows        =       mysql_affected_rows( $database) ;
			if ( $numrows == 1) {
					$row    =       mysql_fetch_assoc( $sqlResult) ;
					$this->assignFromRow( $row) ;
					$this->_valid   =       1 ;
			} else {
				$this->_status  =       -2 ;
			}
		}
		return $this->_status ;
	}

	function	fetchFromDbById( $database) {
		$this->_status	=	0 ;
		$this->_valid	=	0 ;
		$query	=	"select * " ;
		$query	.=	"from TmpLabels " ;

		$query	.=	"where Id='" . $this->Id . "' " ;
		$sqlResult      =       mysql_query( $query, $database) ;
		if ( !$sqlResult) {
			$this->_status  =       -1 ;
		} else {
			$numrows        =       mysql_affected_rows( $database) ;
			if ( $numrows == 1) {
					$row    =       mysql_fetch_assoc( $sqlResult) ;
					$this->assignFromRow( $row) ;
					$this->_valid   =       1 ;
			} else {
				$this->_status  =       -2 ;
			}
		}
		return $this->_status ;
	}

	function	fetchFromDbWhere( $database, $where) {
		$this->_status	=	0 ;
		$this->_valid	=	0 ;
		$query	=	"select * " ;
		$query	.=	"from TmpLabels " ;

		$query	.=	$where ;

		$sqlResult      =       mysql_query( $query, $database) ;
		if ( !$sqlResult) {
			$this->_status  =       -1 ;
		} else {
			$numrows        =       mysql_affected_rows( $database) ;
			if ( $numrows == 1) {
					$row    =       mysql_fetch_assoc( $sqlResult) ;
					$this->assignFromRow( $row) ;
					$this->_valid   =       1 ;
			} else {
				$this->_status  =       -2 ;
			}
		}
		return $this->_status ;
	}

	function	firstFromDb( $database, $where='') {
		$this->_status	=	0 ;
		$this->_valid	=	0 ;
		$this->_currRow	=	0 ;
		$query	=	"select * " ;
		$query	.=	"from TmpLabels " ;
		if ( strlen( $where) > 0) { 
			$query	.=	"where " . $where . " " ;
		} else if ( $this->ArtikelNr != "") { 
			$query	.=	"where ArtikelNr='" . $this->ArtikelNr . "' " ;
		} 
		$sqlResult      =       mysql_query( $query, $database) ;
		if ( !$sqlResult) {
			$this->_status  =       -1 ;
		} else {
			$numrows        =       mysql_affected_rows( $database) ;
			if ( $numrows == 1) {
				$row    =       mysql_fetch_assoc( $sqlResult) ;
				$this->assignFromRow( $row) ;
				$this->_valid   =       1 ;
				$this->_currRow   =       0 ;
				$this->_lastRow   =       0 ;
			} else if ( $numrows > 1) {
				$row    =       mysql_fetch_assoc( $sqlResult) ;
				$this->assignFromRow( $row) ;
				$this->_valid   =       1 ;
				$this->_currRow   =       0 ;
				$this->_lastRow   =       $numrows - 1 ;
			} else {
				$this->_status   =       -5 ;
			}
		}
		return $this->_status ;
	}

	function	nextFromDb( $database, $where='') {
		$this->_status	=	0 ;
		$this->_valid	=	0 ;
		if ( $this->_currRow < $this->_lastRow) { 
			$this->_currRow++ ;
			$query	=	"select * " ;
			$query	.=	"from TmpLabels " ;
			if ( strlen( $where) > 0) { 
				$query	.=	"where " . $where . " " ;
			} else if ( $this->ArtikelNr != "") { 
				$query	.=	"where ArtikelNr='" . $this->ArtikelNr . "' " ;
			}
			$query	.=	"limit ".$this->_currRow.", 1 " ;
			$sqlResult      =       mysql_query( $query, $database) ;
			$row    =       mysql_fetch_assoc( $sqlResult) ;
			$this->assignFromRow( $row) ;
			$this->_valid	=	1 ;
		} else {
			$this->_status	=	-3 ;
		}
		return $this->_status ;
	}

	function	updateInDb( $database) {
		$this->_status	=	0 ;
		$this->_valid	=	0 ;
		$query	=	"update TmpLabels " ;
		$query	.=	"set " ;
		$query	.=	" `ArtikelNrHerst`='" . mysql_escape_string( $this->ArtikelNrHerst) . "' " ;
		$query	.=	",`ArtikelBez1`='" . mysql_escape_string( $this->ArtikelBez1) . "' " ;
		$query	.=	",`ArtikelBez2`='" . mysql_escape_string( $this->ArtikelBez2) . "' " ;
		$query	.=	",`MengenText`='" . mysql_escape_string( $this->MengenText) . "' " ;
		$query	.=	",`VarianteBez`='" . mysql_escape_string( $this->VarianteBez) . "' " ;
		$query	.=	",`MengenEinheit`='" . mysql_escape_string( $this->MengenEinheit) . "' " ;
		$query	.=	",`Gefahrenklasse`='" . mysql_escape_string( $this->Gefahrenklasse) . "' " ;
		$query	.=	",`Aufkleber`='" . mysql_escape_string( $this->Aufkleber) . "' " ;
		$query	.=	",`MengeLabels`='" . mysql_escape_string( $this->MengeLabels) . "' " ;
		$query	.=	"where Id='" . mysql_escape_string( $this->Id) . "' " ;
		$sqlResult      =       mysql_query( $query, $database) ;
		if ( !$sqlResult) {
			$this->_status  =       -1 ;
		} else {
			$this->_valid  =       1 ;
		}
		return $this->_status ;
	}

	function	fullUpdateInDb( $database) {
		$this->_status	=	0 ;
		$this->_valid	=	0 ;
		$query	=	"update TmpLabels " ;
		$query	.=	"set " ;
		$query	.=	" Id='" . mysql_escape_string( $this->Id) . "' " ;
		$query	.=	",ArtikelNr='" . mysql_escape_string( $this->ArtikelNr) . "' " ;
		$query	.=	",ArtikelNrHerst='" . mysql_escape_string( $this->ArtikelNrHerst) . "' " ;
		$query	.=	",ArtikelBez1='" . mysql_escape_string( $this->ArtikelBez1) . "' " ;
		$query	.=	",ArtikelBez2='" . mysql_escape_string( $this->ArtikelBez2) . "' " ;
		$query	.=	",MengenText='" . mysql_escape_string( $this->MengenText) . "' " ;
		$query	.=	",VarianteBez='" . mysql_escape_string( $this->VarianteBez) . "' " ;
		$query	.=	",MengenEinheit='" . mysql_escape_string( $this->MengenEinheit) . "' " ;
		$query	.=	",Gefahrenklasse='" . mysql_escape_string( $this->Gefahrenklasse) . "' " ;
		$query	.=	",Aufkleber='" . mysql_escape_string( $this->Aufkleber) . "' " ;
		$query	.=	",MengeLabels='" . mysql_escape_string( $this->MengeLabels) . "' " ;
		$query	.=	"where Id='" . mysql_escape_string( $this->Id) . "' " ;
		$sqlResult      =       mysql_query( $query, $database) ;
		if ( !$sqlResult) {
			$this->_status  =       -1 ;
		} else {
			$this->_valid  =       1 ;
		}
		return $this->_status ;
	}

	function	removeFromDb( $database) {
		$this->_status	=	0 ;
		$query	=	"delete from TmpLabels " ;
		$query	.=	"where Id='" . mysql_escape_string( $this->Id) . "' " ;
		$query	.=	"limit 1 " ;
		$sqlResult	=	mysql_query( $query, $database) ;
		if ( !$sqlResult) {
			$this->_status	=	-1 ;
		} else {
			$this->_status	=	0 ;
			$this->_valid	=	0 ;
		}
		return $this->_status ;
	}

	function	getFromPost() {
		$this->Id	=	$_POST['_HId'] ;
		$this->ArtikelNr	=	$_POST['_IArtikelNr'] ;
		$this->ArtikelNrHerst	=	$_POST['_IArtikelNrHerst'] ;
		$this->ArtikelBez1	=	$_POST['_IArtikelBez1'] ;
		$this->ArtikelBez2	=	$_POST['_IArtikelBez2'] ;
		$this->MengenText	=	$_POST['_IMengenText'] ;
		$this->VarianteBez	=	$_POST['_IVarianteBez'] ;
		$this->MengenEinheit	=	$_POST['_IMengenEinheit'] ;
		$this->Gefahrenklasse	=	$_POST['_IGefahrenklasse'] ;
		$this->Aufkleber	=	$_POST['_IAufkleber'] ;
		$this->MengeLabels	=	$_POST['_IMengeLabels'] ;
	}

	function	getFromPostL() {
		if ( isset( $_POST['_IArtikelNrHerst'])) { 
			$this->ArtikelNrHerst	=	$_POST['_IArtikelNrHerst'] ;
		}
		if ( isset( $_POST['_IArtikelBez1'])) { 
			$this->ArtikelBez1	=	$_POST['_IArtikelBez1'] ;
		}
		if ( isset( $_POST['_IArtikelBez2'])) { 
			$this->ArtikelBez2	=	$_POST['_IArtikelBez2'] ;
		}
		if ( isset( $_POST['_IMengenText'])) { 
			$this->MengenText	=	$_POST['_IMengenText'] ;
		}
		if ( isset( $_POST['_IVarianteBez'])) { 
			$this->VarianteBez	=	$_POST['_IVarianteBez'] ;
		}
		if ( isset( $_POST['_IMengenEinheit'])) { 
			$this->MengenEinheit	=	$_POST['_IMengenEinheit'] ;
		}
		if ( isset( $_POST['_IGefahrenklasse'])) { 
			$this->Gefahrenklasse	=	$_POST['_IGefahrenklasse'] ;
		}
		if ( isset( $_POST['_IAufkleber'])) { 
			$this->Aufkleber	=	$_POST['_IAufkleber'] ;
		}
		if ( isset( $_POST['_IMengeLabels'])) { 
			$this->MengeLabels	=	$_POST['_IMengeLabels'] ;
		}
	}

	function	dup( $master) {
		$this->Id	=	$master->Id ;
		$this->ArtikelNr	=	$master->ArtikelNr ;
		$this->ArtikelNrHerst	=	$master->ArtikelNrHerst ;
		$this->ArtikelBez1	=	$master->ArtikelBez1 ;
		$this->ArtikelBez2	=	$master->ArtikelBez2 ;
		$this->MengenText	=	$master->MengenText ;
		$this->VarianteBez	=	$master->VarianteBez ;
		$this->MengenEinheit	=	$master->MengenEinheit ;
		$this->Gefahrenklasse	=	$master->Gefahrenklasse ;
		$this->Aufkleber	=	$master->Aufkleber ;
		$this->MengeLabels	=	$master->MengeLabels ;
	}

}
?>
